### ISSUE TITLE
How do I use this?

### ISSUE THREAD

**Issue by yefim** [tj/go-mail#2]
Examples would be much appreciated :)

**Comment by tj** [comment]
haha indeed :D, basically pass in these fields: https://github.com/tj/go-ses/blob/master/ses.go#L17-L21, and `ses.New(session.New(aws.NewConfig()))` to https://github.com/tj/go-ses/blob/master/ses.go#L12

**Comment by yefim** [comment]
Thanks @tj! Figured it out :)
